import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { Providers } from "./provider";

const monse = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Alan Telo | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <head />
      <body className={monse.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
